
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Models.Sail; // Added for SailUtils.ProspectInput
using static Models.Sail.SailUtilities;
using static Models.Prospect.ProspectCore;

namespace Models.Prospect
{
    /// <summary>
    /// Implements the PRO4SAIL model combining PROSPECT and SAIL for canopy reflectance simulation.
    /// </summary>
    /// <remarks>
    /// This class integrates PROSPECT for leaf optical properties and SAIL (4SAIL or 4SAIL2) for canopy reflectance.
    /// Based on the PRO4SAIL function from Lib_PROSAIL.R by Jean-Baptiste Feret and Florian de Boissieu.
    /// Reference: Feret, J.-B., et al. (2019). PROSAIL model.
    /// </remarks>
    public class ProsailCore
    {
        /// <summary>
        /// Runs the PRO4SAIL simulation to compute canopy reflectance factors.
        /// </summary>
        /// <param name="leafOpticalConstants">Leaf optical constants for PROSPECT. If null, loads default from file.</param>
        /// <param name="inputProspectList">List of PROSPECT input parameters from SailUtilities. First element for green leaves, second (optional) for brown leaves.</param>
        /// <param name="N">Leaf structure parameter (unitless). Default is 1.5.</param>
        /// <param name="CAB">Chlorophyll a + b content (μg/cm²). Default is 40.0.</param>
        /// <param name="CAR">Carotenoid content (μg/cm²). Default is 8.0.</param>
        /// <param name="ANT">Anthocyanin content (μg/cm²). Default is 0.0.</param>
        /// <param name="BROWN">Brown pigment content (arbitrary units). Default is 0.0.</param>
        /// <param name="EWT">Equivalent Water Thickness (g/cm²). Default is 0.01.</param>
        /// <param name="LMA">Leaf Mass per Area (g/cm²). Default is 0.008.</param>
        /// <param name="PROT">Protein content (g/cm²). Default is 0.0.</param>
        /// <param name="CBC">Non-protein carbon-based constituent content (g/cm²). Default is 0.0.</param>
        /// <param name="alpha">Incidence angle in degrees. Default is 40.0.</param>
        /// <param name="typeLidf">Type of leaf inclination distribution function (1 for Verhoef, 2 for Campbell). Default is 2.</param>
        /// <param name="lidfA">LIDF parameter a (average leaf slope if typeLidf=1, angle if typeLidf=2). Default is 60.</param>
        /// <param name="lidfB">LIDF parameter b (bimodality if typeLidf=1, null if typeLidf=2). Default is null.</param>
        /// <param name="lai">Leaf Area Index. Default is 3.0.</param>
        /// <param name="q">Hot Spot parameter. Default is 0.1.</param>
        /// <param name="tts">Sun zenith angle in degrees. Default is 30.0.</param>
        /// <param name="tto">Observer zenith angle in degrees. Default is 0.0.</param>
        /// <param name="psi">Relative azimuth angle between sun and observer in degrees. Default is 60.0.</param>
        /// <param name="rsoil">Soil reflectance spectrum. If null, uses default dry soil reflectance.</param>
        /// <param name="fractionBrown">Fraction of brown leaf area (0-1). Default is 0.0.</param>
        /// <param name="diss">Layer dissociation factor (0-1). Default is 0.0.</param>
        /// <param name="cv">Vertical crown cover percentage (0-1). Default is 1.0.</param>
        /// <param name="zeta">Tree shape factor (ratio of crown diameter to height). Default is 1.0.</param>
        /// <param name="sailVersion">SAIL version to use ('4SAIL' or '4SAIL2'). Default is '4SAIL'.</param>
        /// <param name="brownLOP">Brown leaf optical properties. If null, generated by PROSPECT for 4SAIL2 if inputProspectList has two elements.if inputProspectList has two elements. Default is null.</param>
        /// <returns>A SailResult object containing canopy reflectance factors (rdot, rsot, rddt, rsdt, fCover, abs_dir, abs_hem, rsdstar, rddstar).</returns>
        /// <exception cref="ArgumentException">Thrown if input parameters are invalid or array lengths mismatch.</exception>
        /// <exception cref="ArgumentNullException">Thrown if required inputs are null for specific configurations.</exception>
        /// <exception cref="FileNotFoundException">Thrown if spectral data file is missing when leafOpticalConstants is null.</exception>
        public SailResult PRO4SAIL(
            LeafOpticalConsts? leafOpticalConstants = null,
            List<ProspectInputs> inputProspectList = null,
            double N = 1.5,
            double CAB = 40.0,
            double CAR = 8.0,
            double ANT = 0.0,
            double BROWN = 0.0,
            double EWT = 0.01,
            double LMA = 0.008,
            double PROT = 0.0,
            double CBC = 0.0,
            double alpha = 40.0,
            int typeLidf = 2,
            double lidfA = 60.0,
            double? lidfB = null,
            double lai = 3.0,
            double q = 0.1,
            double tts = 30.0,
            double tto = 0.0,
            double psi = 60.0,
            double[] rsoil = null,
            double fractionBrown = 0.0,
            double diss = 0.0,
            double cv = 1.0,
            double zeta = 1.0,
            string sailVersion = "4SAIL",
            LeafOptics? brownLOP = null)
        {
            // Validate inputs
            if (!new[] { "4SAIL", "4SAIL2" }.Contains(sailVersion))
                throw new ArgumentException("SAILversion must be '4SAIL' or '4SAIL2'.");
            if (fractionBrown < 0 || fractionBrown > 1)
                throw new ArgumentOutOfRangeException(nameof(fractionBrown), "fractionBrown must be between 0 and 1.");
            if (diss < 0 || diss > 1)
                throw new ArgumentOutOfRangeException(nameof(diss), "diss must be between 0 and 1.");
            if (cv < 0 || cv > 1)
                throw new ArgumentOutOfRangeException(nameof(cv), "Cv must be between 0 and 1.");
            if (zeta < 0)
                throw new ArgumentOutOfRangeException(nameof(zeta), "Zeta cannot be negative.");
            if (typeLidf != 1 && typeLidf != 2)
                throw new ArgumentException("TypeLidf must be 1 (Verhoef) or 2 (Campbell).");
            if (typeLidf == 1 && !lidfB.HasValue)
                throw new ArgumentException("LIDFb is required when TypeLidf is 1.");

            // Load spectral constants if not provided
            LeafOpticalConsts leafOpticalData = leafOpticalConstants ?? LoadLocalOpticalData();

            // Default soil reflectance
            if (rsoil == null)
            {
                // Assuming dry soil reflectance is a flat 0.2 across all wavelengths (simplified)
                // In practice, load from a predefined dataset or file matching SpecSOIL$Dry_Soil
                rsoil = Enumerable.Repeat(0.2, leafOpticalData.Wavelength.Count).ToArray();
            }

            // Validate rsoil length
            if (rsoil.Length != leafOpticalData.Wavelength.Count)
                throw new ArgumentException("Soil reflectance array length must match spectral data wavelengths.");

            // Prepare PROSPECT inputs
            if (inputProspectList == null || inputProspectList.Count == 0)
            {
                inputProspectList = new List<ProspectInputs>
                {
                    new ProspectInputs(
                        N, CAB, CAR, ANT, BROWN, EWT, LMA, PROT, cbc: CBC, alpha: alpha)
                };
            }

            // Adjust PROSPECT inputs for SAIL
            AdjustedProspectResult adjustedResults = AdjustProspectToSail(
                  sailVersion: sailVersion, 
                  leafOpticalConstants: leafOpticalData, 
                  inputProspectList: inputProspectList, 
                  fractionBrown: fractionBrown, 
                  brownLOP: brownLOP.HasValue ? brownLOP: null);

            // Prepare soil properties
            var soilProperties = new SoilProperties { Reflectance = rsoil };

            // Run SAIL simulation based on version
            SailResult result;
            if (sailVersion == "4SAIL")
            {
                result = SailCore.FourSAIL(
                    leafOptics: adjustedResults.GreenLOP,
                    typeLidf: typeLidf,
                    lidfA: lidfA,
                    lidfB: lidfB,
                    lai: lai,
                    q: q,
                    tts: tts,
                    tto: tto,
                    psi: psi,
                    soilProperties: soilProperties);
            }
            else // 4SAIL2
            {
                result = SailCore.FourSAIL2(
                    leafGreen: adjustedResults.GreenLOP,
                    leafBrown: (LeafOptics)adjustedResults.BrownLOP,
                    typeLidf: typeLidf,
                    lidfA: lidfA,
                    lidfB: lidfB,
                    lai: lai,
                    q: q,
                    tts: tts,
                    tto: tto,
                    psi: psi,
                    soilProperties: soilProperties,
                    fractionBrown: fractionBrown,
                    diss: diss,
                    cv: cv,
                    zeta: zeta);
            }

            return result;
        }
    }
}