using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using APSIM.Shared.Utilities;
using static Models.PROSAIL.SAIL.SailUtilities;
using static Models.PROSAIL.PROSPECT.ProspectCore;
using MathNet.Numerics;
using MathNet.Numerics.LinearAlgebra;
using Models.PROSAIL.Sail;


namespace Models.Prosail
{
    /// <summary>
    /// Implements the PRO4SAIL model combining PROSPECT and SAIL for canopy reflectance simulation.
    /// </summary>
    /// <remarks>
    /// This class integrates PROSPECT for leaf optical properties and SAIL (4SAIL or 4SAIL2) for canopy reflectance.
    /// Based on the PRO4SAIL function from Lib_PROSAIL.R by Jean-Baptiste Feret and Florian de Boissieu.
    /// Reference: Feret, J.-B., et al. (2019). PROSAIL model.
    /// </remarks>
    public class ProsailCore
    {
        /// <summary>
        /// Runs the PRO4SAIL simulation to compute canopy reflectance factors.
        /// </summary>
        /// <param name="leafOpticalConstants">Leaf optical constants for PROSPECT. If null, loads default from file.</param>
        /// <param name="inputProspectList">List of PROSPECT input parameters from SailUtilities. First element for green leaves, second (optional) for brown leaves.</param>
        /// <param name="N">Leaf structure parameter (unitless). Default is 1.5.</param>
        /// <param name="CAB">Chlorophyll a + b content (μg/cm²). Default is 40.0.</param>
        /// <param name="CAR">Carotenoid content (μg/cm²). Default is 8.0.</param>
        /// <param name="ANT">Anthocyanin content (μg/cm²). Default is 0.0.</param>
        /// <param name="BROWN">Brown pigment content (arbitrary units). Default is 0.0.</param>
        /// <param name="EWT">Equivalent Water Thickness (g/cm²). Default is 0.01.</param>
        /// <param name="LMA">Leaf Mass per Area (g/cm²). Default is 0.008.</param>
        /// <param name="PROT">Protein content (g/cm²). Default is 0.0.</param>
        /// <param name="CBC">Non-protein carbon-based constituent content (g/cm²). Default is 0.0.</param>
        /// <param name="Alpha">Incidence angle in degrees. Default is 40.0.</param>
        /// <param name="Wavelengths">Array of specific wavelengths to simulate (subset of OpticalConstants.Wavelength, if null, all wavelengths used).</param>
        /// <param name="TypeLidf">Type of leaf inclination distribution function (1 for Verhoef, 2 for Campbell). Default is 2.</param>
        /// <param name="LIDFa">LIDF parameter a (average leaf slope if TypeLidf=1, angle if TypeLidf=2). Default is 60.</param>
        /// <param name="LIDFb">LIDF parameter b (bimodality if TypeLidf=1, null if TypeLidf=2). Default is null.</param>
        /// <param name="LAI">Leaf Area Index. Default is 3.0.</param>
        /// <param name="HotSpot">Hot Spot parameter (0-1). Default is 0.1.</param>
        /// <param name="TTS">Sun zenith angle in degrees (0-90). Default is 30.0.</param>
        /// <param name="TTO">Observer zenith angle in degrees (0-90). Default is 0.0.</param>
        /// <param name="PSI">Relative azimuth angle between sun and observer in degrees (0-360). Default is 60.0.</param>
        /// <param name="SoilReflectance">An object of SoilOptics strcut containing wavelengths and soil reflectance spectrum.</param>
        /// <param name="FractionBrown">Fraction of brown leaf area (0-1). Default is 0.0.</param>
        /// <param name="Diss">Layer dissociation factor (0-1). Default is 0.0.</param>
        /// <param name="Cv">Vertical crown cover percentage (0-1). Default is 1.0.</param>
        /// <param name="Zeta">Tree shape factor (ratio of crown diameter to height, positive). Default is 1.0.</param>
        /// <param name="SailVersion">SAIL version to use ('4SAIL' or '4SAIL2'). Default is '4SAIL'.</param>
        /// <param name="BrownLOP">Brown leaf optical properties. If null, generated by PROSPECT for 4SAIL2 if inputProspectList has two elements.if inputProspectList has two elements. Default is null.</param>
        /// <returns>A CanopyOptics object containing canopy reflectance factors (rdot, rsot, rddt, rsdt, fCover, abs_dir, abs_hem, rsdstar, rddstar).</returns>
        /// <exception cref="ArgumentException">Thrown if input parameters are invalid or array lengths mismatch.</exception>
        /// <exception cref="ArgumentNullException">Thrown if required inputs are null for specific configurations.</exception>
        /// <exception cref="FileNotFoundException">Thrown if spectral data file is missing when leafOpticalConstants is null.</exception>
        public static CanopyOptics PRO4SAIL(
            LeafOpticalConsts? leafOpticalConstants = null,
            List<ProspectInputs> inputProspectList = null,
            double N = 1.5,
            double CAB = 40.0,
            double CAR = 8.0,
            double ANT = 0.0,
            double BROWN = 0.0,
            double EWT = 0.01,
            double LMA = 0.008,
            double PROT = 0.0,
            double CBC = 0.0,
            double Alpha = 40.0,
            double[] Wavelengths = null,
            int TypeLidf = 2,
            double LIDFa = 60.0,
            double? LIDFb = null,
            double LAI = 3.0,
            double HotSpot = 0.1,
            double TTS = 30.0,
            double TTO = 0.0,
            double PSI = 60.0,
            SoilOptics SoilReflectance = default,
            double FractionBrown = 0.0,
            double Diss = 0.0,
            double Cv = 1.0,
            double Zeta = 1.0,
            string SailVersion = "4SAIL",
            LeafOptics? BrownLOP = null)
        {
            // Validate inputs
            if (!new[] { "4SAIL", "4SAIL2" }.Contains(SailVersion))
                throw new ArgumentException("SAILversion must be '4SAIL' or '4SAIL2'.");
            if (FractionBrown < 0 || FractionBrown > 1)
                throw new ArgumentOutOfRangeException(nameof(FractionBrown), "fractionBrown must be between 0 and 1.");
            if (Diss < 0 || Diss > 1)
                throw new ArgumentOutOfRangeException(nameof(Diss), "diss must be between 0 and 1.");
            if (Cv < 0 || Cv > 1)
                throw new ArgumentOutOfRangeException(nameof(Cv), "Cv must be between 0 and 1.");
            if (Zeta < 0)
                throw new ArgumentOutOfRangeException(nameof(Zeta), "Zeta cannot be negative.");
            if (TypeLidf != 1 && TypeLidf != 2)
                throw new ArgumentException("TypeLidf must be 1 (Verhoef) or 2 (Campbell).");
            if (TypeLidf == 1 && !LIDFb.HasValue)
                throw new ArgumentException("LIDFb is required when TypeLidf is 1.");

            // Load spectral constants if not provided
            LeafOpticalConsts leafOpticalData = leafOpticalConstants ?? GetCachedLeafOpticalConstants();

            // Prepare PROSPECT inputs
            if (inputProspectList == null || inputProspectList.Count == 0)
            {
                inputProspectList = new List<ProspectInputs>
                {
                    new ProspectInputs(
                        n:N, cab:CAB, car:CAR, ant:ANT, brown:BROWN, ewt:EWT, lma:LMA, prot:PROT, cbc: CBC, alpha: Alpha, wavelengths:Wavelengths)
                };
            }

            // Adjust PROSPECT inputs for SAIL
            AdjustedProspectResult adjustedResults = AdjustProspectToSail(
                  sailVersion: SailVersion, 
                  leafOpticalConstants: leafOpticalData, 
                  inputProspectList: inputProspectList, 
                  fractionBrown: FractionBrown, 
                  brownLOP: BrownLOP.HasValue ? BrownLOP: null);

            // Run SAIL simulation based on version. AdjustProspectToSail may have fallen back to
            // a green-only result (e.g. 4SAIL2 requested but only one PROSPECT input set was
            // available to build a brown LOP) - honour that fallback here too, rather than
            // trusting the originally-requested SailVersion, otherwise BrownLOP would be null
            // and the cast below would throw.
            CanopyOptics result;
            if (SailVersion == "4SAIL" || !adjustedResults.BrownLOP.HasValue)
            {
                result = SailCore.FourSAIL(
                    leafOptics: adjustedResults.GreenLOP,
                    typeLidf: TypeLidf,
                    lidfA: LIDFa,
                    lidfB: LIDFb,
                    lai: LAI,
                    q: HotSpot,
                    tts: TTS,
                    tto: TTO,
                    psi: PSI,
                    soilOptics: SoilReflectance);
            }
            else // 4SAIL2
            {
                result = SailCore.FourSAIL2(
                    leafGreen: adjustedResults.GreenLOP,
                    leafBrown: adjustedResults.BrownLOP.Value,
                    typeLidf: TypeLidf,
                    lidfA: LIDFa,
                    lidfB: LIDFb,
                    lai: LAI,
                    q: HotSpot,
                    tts: TTS,
                    tto: TTO,
                    psi: PSI,
                    soilOptics: SoilReflectance,
                    fractionBrown: FractionBrown,
                    diss: Diss,
                    cv: Cv,
                    zeta: Zeta);
            }

            return result;
        }
    }
}